language: python
python:
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - pypy
env:
  - DJANGO="<2.2"
  - DJANGO="<2.2.1"
  - DJANGO="<2.2.2"
  - DJANGO="<2.2.3"
  - DJANGO="<2.2.4"
  - DJANGO="<2.2.5"
  - DJANGO="<2.2.6"
  - DJANGO="<2.2.7"
  - DJANGO="<2.2.8"
  - DJANGO="<2.2.9"
  - DJANGO="<2.2.10"
  - DJANGO="<2.2.11"
  - DJANGO="<2.2.12"
  - DJANGO="<2.2.13"
  - DJANGO="<2.2.14"
 
  - DJANGO="<3.0"
  - DJANGO="<3.0.1"
  - DJANGO="<3.0.2"
  - DJANGO="<3.0.3"
  - DJANGO="<3.0.4"
  - DJANGO="<3.0.5"
  - DJANGO="<3.0.6"
  - DJANGO="<3.0.7"
  - DJANGO="<3.0.8"
  - DJANGO="<3.0.9"
  
  
before_install:
  - export DJANGO_SETTINGS_MODULE=jet.tests.settings
install:
  - pip install -q "Django${DJANGO}"
  - pip install .
  - pip install coverage==3.7.1
  - pip install coveralls==0.5
script:
  - coverage run --source=jet --omit=*/migrations/*,*/south_migrations/*,*/tests/* manage.py test jet
after_success:
  - coverage report
  - coveralls
